version: 2.1


jobs:
  run-sca-tool-nodejsscan:
    working_directory: /src
    description: Scan Javascript package dependencies
    docker:
    - image: python:slim
    steps:
      - checkout
      - deploy:
          name:
          command: |
              mkdir -p /tmp/artifacts
              touch /tmp/artifacts/results-nodejsscan.json
              pip install nodejsscan
              nodejsscan -d /src -o /tmp/artifacts/results-nodejsscan.json
      - store_artifacts:
          path: /tmp/artifacts

  run-sca-tool-brakeman:
    working_directory: /src
    description: Brakeman Scan
    docker:
      - image: ruby:alpine3.12
    steps:
      - checkout
      - deploy:
          command: |
            apk update && apk add curl wget bash
            apk add ruby ruby-io-console ruby-bundler
            gem install brakeman
            mkdir -p /tmp/artifacts
            brakeman -d /src -o /tmp/artifacts/results-brakeman.html
      - store_artifacts:
          path: /tmp/artifacts

#   pmd:
#     description: Scan code using PMD 
#     machine: true
#     steps:
#       - checkout  
#       - run:
#           command: |
#                 mkdir -p /tmp/artifacts
#                 touch /tmp/artifacts/results-pmd.html
#                 cd $HOME
#                 wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.23.0/pmd-bin-6.23.0.zip
#                 unzip pmd-bin-6.23.0.zip
#                 cd pmd-bin-6.23.0/bin/
#                 chmod +x run.sh
#                 if ./run.sh pmd -dir /home/circleci/project/app1/ -f html -rulesets rulesets/java/quickstart.xml,category/java/codestyle.xml > /tmp/artifacts/results-pmd.html; then exit 0; fi
#           name: Run PMD Scan on Property-repo
#       - store_artifacts:
#           path: /tmp/artifacts

workflows:
  version: 2.1
  build:
    triggers:
      - schedule:
                #"Min Hour Day Month Day_of_week"
          cron: "55 8 * * *"
          filters:
            branches:
              only:
                - sca-scan

    jobs:
      - run-sca-tool-brakeman
      - run-sca-tool-nodejsscan



















